### PR TITLE
UV Manipulator, Part 1

### PR DESCRIPTION
**Pull request by peteihis**
Code reformatting fro readability. There were hardly any indentations and there were really deep nested blocks. 

EDIT:
I seem to have branched this from the branch of #19. It should have been from my current master branch. I don't think it hurts if #19 accepted but I'll rebase if necessary (preferably only if necessary).

### CODE REVIEW

**Comment by Sailsman63** [comment]
It would cause issues if I had already merged #19. In this case, I'll just handle it all with this PR, so don't worry.

**Comment by peteihis** [comment]
> It would cause issues if I had already merged #19.

So what would have been the issue? #19 removes unused files and #20 modifies some other files. What is the interaction?

**Comment by Sailsman63** [comment]
If I merged #19 independently, there would be a merge commit in between. In some cases, this leads to wierd interactions where the more recent PR  tries to re-apply the previously merged changes. This is more of an issue when Daisy-chaining PRs that requires other changes first, which is why I was hoping that I could review and merge a change before you opened the next PR.

**Comment by peteihis** [comment]
>  this leads to weird interactions 

Well, a different thing but I have noticed that some times rebasing in the local git begins to see things, that shouldn't be there any more.... Some times the cure has been hard reset and sometimes I just copy the steps and rewrite into a new branch.

**\<edit\>** It just is that, when I am at something, it is better to keep working on it. If I have to stop and wait, picking up, what I left behind, is much harder.**\</edit\>** 

If you'd prefer to merge everything one by one, I can rebase/rebuild the latter PRs to the new master as soon as the previous one is merged. Now #21 follows #20 as chain and #18  follows #17.

And I started to study the MeshPreviewer file. There is the mouse button stuff in #10 that I'd like to have in the base of fixing the wire frame drawing. Or maybe I'll just add commits to PR #10? It is loosely related. (On that file there are entirely different matrices for rendering the surfaces and drawing the wire frame shape. No wonder they don't match. I've got to check, how it is done in the 'real' viewers.)

Unfortunately I was not systematical in reformatting the MeshPreviewer style in 10. Only did a 'light version' to get the main concerns done. I guess I should do the remaining parts too.

**Comment by Sailsman63** [comment]
I'll just look at these together now... don't worry about it.

As for #10 and loosely related... no. Let me finish reviewing that first, and merge it. If you want to do more reformat, keep it as a separate commit on a new PR. (Once #10 is merged)

**Comment by Sailsman63** [comment]
Okay, looks like this bit is _all_ reformat. Will merge.

**Pull request merged**
