### PR TITLE
Suspicious vertex init

### PR DESCRIPTION
**Pull request by makiam**
Probably erroneous vertex calculation fix. All case subexpressions was identical. Now fills vertex value from v1, v2 and v3 accordingly

### CODE REVIEW

**Comment by Sailsman63** [comment]
Can you do some digging and find out what causes this code to be called? I'm hesitant to change code without understanding it.

**Comment by makiam** [comment]
Affects only convertToTriangleMesh method. Other execution conditions:
smoothingMethod != Mesh.APPROXIMATING
and Object3D ParameterValue[] array  != null
and arbitrary ParameterValue is FaceVertexParameterValue

**Comment by peteihis** [comment]
For some reason this PO has been left hanging. The code has changed so much that there's no point trying to rebase, but the main point is still valid! The `v1`× 3 should be ` v1` , `v2`, and `v3`.

The bug is that, when you convert a PolyMesh with UV texture into a TriangleMesh and the PME is set to `Smoothing Method = None`, the inherited texture is mapped to a single point of the face. The fix did not affect, when the PME was set `Approximating'. In that case the inherited texture is just wrinkled in either case.

v1-fix

_**Left:** PME as is, **middle:** TME by the current converter, **right:** with the "v1-fix"_

The lines of the `switch case` are 3007 through 3017 in the current code.

Other than that `Vector`s from line 99 forward are nowadays `List`s  on lines 95 - 97 and the `Pas treuvé`s (="Not found") are _(very obviously)_ debugging code and should be removed.

**Comment by makiam** [comment]
[VERTEX_INIT_FIX.PATCH](https://github.com/ArtOfIllusion/Polymesh/files/14356340/VERTEX_INIT_FIX.PATCH)

**Comment by Sailsman63** [comment]
> For some reason this PO has been left hanging. 

That's because, until your post, we didn't have a confirmed bug, just a bit of code that looked suspicious.

Will look at patching tomorrow.

**Comment by peteihis** [comment]
Better late than never I guess.... :)

The other issue -- wrinkly image on the smoothed piece is a more complex one to sort out. 

In those in the picture there just was the approximating on and the conversion was done with as little subdividing as possible. The mapping of the rendering mesh is off at least for some corners of triangles, but which ones and how, I haven't been able to figure out.

One partial culprit is the Catmull-Clark smoothing that is only smooth if you keep using it on itself several times over. The first iteration overshoots or undershoots the vertex positions and, when that result is triangulated, the triangle mesh even has inward dents!

But that's not all. No matter how much you smooth the mesh, the triangles always seem to have the same relative amount of mapping error. It just gets smaller along with the triangles. Somehow that does not happen with the rendering mesh that PME provides, though the code seems to recycle the same processes for different purposes.

**Comment by peteihis** [comment]
>  wrinkly image on the smoothed piece 

It looks like the bug weren't in PME, but in Rendering mesh production of TriangleMesh. The mapping on the image is correct but the mid points on the short edges of a subdivided triangle are in a wrong position in the space. ... That at least narrows down, where to look.

**Comment by Sailsman63** [comment]
> in Rendering mesh production of TriangleMesh. The mapping on the image is correct but the mid points on the short edges of a subdivided triangle are in a wrong position in the space. ... That at least narrows down, where to look.

Is this something that comes up with similar, hand-built/hand-mapped Triangle meshes? Or only ones that have been exported from PME?

**Comment by peteihis** [comment]
> Is this something that comes up with similar, hand-built/hand-mapped Triangle meshes? Or only ones that have been exported from PME?

That will take some time to figure out.... TriangleMesh has three methods, `blend` for 2D and 3D and `setBlend` to subdivide a mesh. The `blend` methods subdivide edges and `setBlend` repositions the vertices according to smoothing. There are 5 calls to blend and 27 to setBlend in different circumstances...

So far it seems that the PME exported mesh uses mostly the same few of them and I found the one that seems to produce the problem in most of the cases but not all. On a TriangelMesh converted from a Sphere I saw an illogical mapping-position mismatch too but that was clearly a different one and in that particular case it did not hurt visually, just logically, so that one was obviously intentional.

That one corner of a triangle is close to orthogonal is a somehow factor in the PME-converted case. The problem appears on the short edges of that kind of a triangle. That is not to say, there could not be others.

**Comment by peteihis** [comment]
> Or only ones that have been exported from PME?

At least it is not entirely unique to PME converts. 

What I though I saw on a Sphere converted to Trimesh earlier is actually correct, but a converted Spline mesh produced wrinkles. Not identical to the PME case but with a lot of similarities, like that some of the split lines follow a strange zic-zac pattern. When there is "zic" somewhere, there is a "zac" exactly on the opposite side of a symmetry center (what ever the converter considers a symmetry center). 

Which way the "countersymmetry" appears, would seem to depend on how the vertex positions have been unfolded to uv-world. Indexing order may be a factor, but not the root cause.

**Comment by Sailsman63** [comment]
Thanks! Finally got back to this.

**Pull request closed without merging**
